/**
 * Writes the Content-Security-Policy into dist/_headers.
 *
 * The site shipped without a CSP. Every other security header was in place —
 * HSTS with preload, nosniff, frame-options, referrer-policy, permissions-policy
 * — but CSP is the one that limits the damage if a script ever does reach a
 * page, and on a site holding children's records that is the one worth having.
 *
 * The hash is computed here rather than written by hand. index.html carries one
 * inline script (the theme snippet that prevents a light flash before React
 * loads), and hashing it means script-src does not need 'unsafe-inline', which
 * would let any injected inline script run and largely defeat the point.
 * Hardcoding the hash would break silently the first time that snippet is
 * edited: the theme would flash and nothing would say why.
 *
 * The allowed origins are not guessed either — they are the four the site
 * actually loads from, measured by driving every page and recording each
 * request: itself, Google Fonts' stylesheet and font hosts, and the API.
 *
 * Runs after prerender, so it sees the final HTML.
 */
import { readFileSync, writeFileSync, existsSync, appendFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const clientRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const distDir = resolve(clientRoot, 'dist')
const indexHtml = resolve(distDir, 'index.html')

if (!existsSync(indexHtml)) {
  throw new Error('generate-csp: dist/index.html is missing. Run this after the build.')
}

const html = readFileSync(indexHtml, 'utf8')

/** Executable inline scripts only — ld+json is data and CSP does not run it. */
const inlineScripts = [...html.matchAll(/<script(?![^>]*\ssrc=)([^>]*)>([\s\S]*?)<\/script>/g)]
  .filter((match) => !/application\/ld\+json/.test(match[1]))
  .map((match) => match[2])

/**
 * Newlines are normalised before hashing, and this is not cosmetic.
 *
 * The HTML parser converts CRLF and CR to LF before a script's text is hashed
 * for CSP, and this repository checks out with CRLF on Windows. Hashing the
 * bytes on disk therefore produced a hash no browser ever computes, and the
 * policy blocked the very script it was written to allow — on every page.
 *
 * Caught by deploying to a preview URL and driving it. It could not have been
 * caught any other way: the file, the served bytes and the computed hash all
 * looked correct in isolation, and only the browser disagreed.
 */
const CR = String.fromCharCode(13)
const LF = String.fromCharCode(10)

const hashes = inlineScripts.map((source) => {
  const normalised = source.split(CR + LF).join(LF).split(CR).join(LF)
  return `'sha256-${createHash('sha256').update(normalised, 'utf8').digest('base64')}'`
})

if (inlineScripts.length === 0) {
  console.warn('generate-csp: found no inline scripts. If one was expected, the CSP may block it.')
}

const API_ORIGIN = (process.env.VITE_API_URL || 'http://localhost:5000/api')
  .replace(/\/api\/?$/, '')
  .replace(/\/$/, '')

const policy = [
  `default-src 'self'`,
  // Hashed, so an injected inline script is refused.
  `script-src 'self' ${hashes.join(' ')}`.trim(),
  // Styles still need 'unsafe-inline': React writes style attributes and the
  // build emits a <style> block, and neither can be hashed usefully. Inline
  // style cannot execute script, so this is a far smaller concession.
  `style-src 'self' 'unsafe-inline' https://fonts.googleapis.com`,
  `font-src 'self' https://fonts.gstatic.com`,
  `img-src 'self' data: blob:`,
  `connect-src 'self' ${API_ORIGIN}`,
  `frame-ancestors 'self'`,
  `base-uri 'self'`,
  `form-action 'self'`,
  `object-src 'none'`,
].join('; ')

const headers = `# Generated by scripts/generate-csp.mjs — do not edit by hand.
# The script hash is recomputed on every build from the inline snippet in
# index.html, so editing that snippet cannot leave a stale hash behind.
/*
  Content-Security-Policy: ${policy}
`

const headersFile = resolve(distDir, '_headers')
if (existsSync(headersFile)) {
  appendFileSync(headersFile, '\n' + headers)
} else {
  writeFileSync(headersFile, headers)
}

console.log(`csp: ${inlineScripts.length} inline script(s) hashed, API origin ${API_ORIGIN}`)

/**
 * The same rules again, in Apache's dialect, for serving the site from cPanel.
 *
 * Written by this script rather than kept by hand because the policy above
 * contains a script hash that changes whenever the inline theme snippet is
 * edited. A hand-maintained copy would go stale silently and start blocking
 * the very script it was written to allow.
 *
 * Emitted as a fragment with markers rather than a whole .htaccess: the live
 * file also carries cPanel's own PHP directives and an HTTPS redirect, and the
 * deploy step replaces only the block between these markers.
 */
let SITE_URL = process.env.VITE_SITE_URL || 'https://www.axislearning.co.ke'
if (SITE_URL.endsWith('/')) SITE_URL = SITE_URL.slice(0, -1)
const siteHost = new URL(SITE_URL).host
const apexHost = siteHost.startsWith('www.') ? siteHost.slice(4) : siteHost
// Dots are matched with a character class so no escaping has to survive the
// journey from this template into the .htaccess file.
const apexPattern = apexHost.split('.').join('[.]')
const apexRedirect =
  siteHost === apexHost
    ? '  # The canonical host has no www form, so there is nothing to redirect.'
    : [
        '  # Every canonical tag and the sitemap name the www host. Netlify',
        '  # redirected the bare domain to it; Apache serves both unless told',
        '  # otherwise, which would publish the whole site twice.',
        '  RewriteCond %{HTTP_HOST} ^' + apexPattern + '$ [NC]',
        '  RewriteRule ^(.*)$ ' + SITE_URL + '/$1 [L,R=301]',
      ].join(String.fromCharCode(10))

const htaccess = `# BEGIN axis-learning — generated by scripts/generate-csp.mjs, do not edit by hand
<IfModule mod_headers.c>
  Header always set Content-Security-Policy "${policy}"
  Header always set X-Frame-Options "SAMEORIGIN"
  Header always set X-Content-Type-Options "nosniff"
  Header always set Referrer-Policy "strict-origin-when-cross-origin"
  Header always set Permissions-Policy "geolocation=(), microphone=(), camera=()"

  # Asset filenames are content-hashed, so they can be cached indefinitely.
  SetEnvIf Request_URI "^/assets/" AXIS_IMMUTABLE
  Header set Cache-Control "public, max-age=31536000, immutable" env=AXIS_IMMUTABLE

  # HTML is regenerated on every deploy and must not be served stale.
  <FilesMatch "[.]html$">
    Header set Cache-Control "public, max-age=0, must-revalidate"
  </FilesMatch>

  <Files "sitemap.xml">
    Header set Cache-Control "public, max-age=3600"
  </Files>
</IfModule>

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /

${apexRedirect}

  # A real file wins outright: prerendered HTML, hashed assets, the sitemap.
  RewriteCond %{REQUEST_FILENAME} -f
  RewriteRule ^ - [L]

  # The admin panel and the portals are rendered by the client, so they are
  # served the shell with a 200 rather than a prerendered page.
  RewriteRule ^admin(/.*)?$ /app.html [L]
  RewriteRule ^portal(/.*)?$ /app.html [L]

  # Prerendered pages are written as <route>/index.html. Left alone, Apache
  # answers /about with a 301 to /about/ — but the sitemap and the page's own
  # canonical tag both say /about, so the redirect would hand crawlers a URL
  # that disagrees with the page it lands on. Rewriting internally keeps the
  # advertised URL the one that actually answers.
  RewriteCond %{DOCUMENT_ROOT}/$1/index.html -f
  RewriteRule ^(.+?)/?$ /$1/index.html [L]
</IfModule>

# Anything with no file behind it is genuinely not a page. The shell still
# boots and renders the app's own not-found view, but the status tells crawlers
# the truth. This serves app.html — a pristine noindex shell — and never
# index.html, which is the prerendered homepage and would answer every mistyped
# URL with homepage markup and a site-root canonical.
ErrorDocument 404 /app.html
# END axis-learning
`

writeFileSync(resolve(distDir, 'axis.htaccess'), htaccess)
console.log('htaccess: wrote dist/axis.htaccess for the cPanel deploy')

