/**
 * Writes the Content-Security-Policy into dist/_headers.
 *
 * The site shipped without a CSP. Every other security header was in place —
 * HSTS with preload, nosniff, frame-options, referrer-policy, permissions-policy
 * — but CSP is the one that limits the damage if a script ever does reach a
 * page, and on a site holding children's records that is the one worth having.
 *
 * The hash is computed here rather than written by hand. index.html carries one
 * inline script (the theme snippet that prevents a light flash before React
 * loads), and hashing it means script-src does not need 'unsafe-inline', which
 * would let any injected inline script run and largely defeat the point.
 * Hardcoding the hash would break silently the first time that snippet is
 * edited: the theme would flash and nothing would say why.
 *
 * The allowed origins are not guessed either — they are the four the site
 * actually loads from, measured by driving every page and recording each
 * request: itself, Google Fonts' stylesheet and font hosts, and the API.
 *
 * Runs after prerender, so it sees the final HTML.
 */
import { readFileSync, writeFileSync, existsSync, appendFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const clientRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const distDir = resolve(clientRoot, 'dist')
const indexHtml = resolve(distDir, 'index.html')

if (!existsSync(indexHtml)) {
  throw new Error('generate-csp: dist/index.html is missing. Run this after the build.')
}

const html = readFileSync(indexHtml, 'utf8')

/** Executable inline scripts only — ld+json is data and CSP does not run it. */
const inlineScripts = [...html.matchAll(/<script(?![^>]*\ssrc=)([^>]*)>([\s\S]*?)<\/script>/g)]
  .filter((match) => !/application\/ld\+json/.test(match[1]))
  .map((match) => match[2])

/**
 * Newlines are normalised before hashing, and this is not cosmetic.
 *
 * The HTML parser converts CRLF and CR to LF before a script's text is hashed
 * for CSP, and this repository checks out with CRLF on Windows. Hashing the
 * bytes on disk therefore produced a hash no browser ever computes, and the
 * policy blocked the very script it was written to allow — on every page.
 *
 * Caught by deploying to a preview URL and driving it. It could not have been
 * caught any other way: the file, the served bytes and the computed hash all
 * looked correct in isolation, and only the browser disagreed.
 */
const CR = String.fromCharCode(13)
const LF = String.fromCharCode(10)

const hashes = inlineScripts.map((source) => {
  const normalised = source.split(CR + LF).join(LF).split(CR).join(LF)
  return `'sha256-${createHash('sha256').update(normalised, 'utf8').digest('base64')}'`
})

if (inlineScripts.length === 0) {
  console.warn('generate-csp: found no inline scripts. If one was expected, the CSP may block it.')
}

const API_ORIGIN = (process.env.VITE_API_URL || 'http://localhost:5000/api')
  .replace(/\/api\/?$/, '')
  .replace(/\/$/, '')

const policy = [
  `default-src 'self'`,
  // Hashed, so an injected inline script is refused.
  `script-src 'self' ${hashes.join(' ')}`.trim(),
  // Styles still need 'unsafe-inline': React writes style attributes and the
  // build emits a <style> block, and neither can be hashed usefully. Inline
  // style cannot execute script, so this is a far smaller concession.
  `style-src 'self' 'unsafe-inline' https://fonts.googleapis.com`,
  `font-src 'self' https://fonts.gstatic.com`,
  `img-src 'self' data: blob:`,
  `connect-src 'self' ${API_ORIGIN}`,
  `frame-ancestors 'self'`,
  `base-uri 'self'`,
  `form-action 'self'`,
  `object-src 'none'`,
].join('; ')

const headers = `# Generated by scripts/generate-csp.mjs — do not edit by hand.
# The script hash is recomputed on every build from the inline snippet in
# index.html, so editing that snippet cannot leave a stale hash behind.
/*
  Content-Security-Policy: ${policy}
`

const headersFile = resolve(distDir, '_headers')
if (existsSync(headersFile)) {
  appendFileSync(headersFile, '\n' + headers)
} else {
  writeFileSync(headersFile, headers)
}

console.log(`csp: ${inlineScripts.length} inline script(s) hashed, API origin ${API_ORIGIN}`)
